# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commonpb/common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ommonpb/common.proto\x12\x08\x63ommonpb\"\x07\n\x05\x45mpty\" \n\x04\x41\x64\x64r\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\"I\n\x08\x41\x64\x64rPack\x12\x1d\n\x05local\x18\x01 \x01(\x0b\x32\x0e.commonpb.Addr\x12\x1e\n\x06remote\x18\x02 \x01(\x0b\x32\x0e.commonpb.AddrB-Z+github.com/Veids/grdp2tcp/protobuf/commonpbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'commonpb.common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z+github.com/Veids/grdp2tcp/protobuf/commonpb'
  _EMPTY._serialized_start=35
  _EMPTY._serialized_end=42
  _ADDR._serialized_start=44
  _ADDR._serialized_end=76
  _ADDRPACK._serialized_start=78
  _ADDRPACK._serialized_end=151
# @@protoc_insertion_point(module_scope)
