# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clientpb/client.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from commonpb import common_pb2 as commonpb_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63lientpb/client.proto\x12\x08\x63lientpb\x1a\x15\x63ommonpb/common.proto\"!\n\x0c\x45ndpointList\x12\x11\n\tendpoints\x18\x01 \x03(\t2\xfe\x01\n\tClientRpc\x12-\n\nSocksStart\x12\x0e.commonpb.Addr\x1a\x0f.commonpb.Empty\x12,\n\tSocksStop\x12\x0e.commonpb.Addr\x1a\x0f.commonpb.Empty\x12\x33\n\x0cReverseStart\x12\x12.commonpb.AddrPack\x1a\x0f.commonpb.Empty\x12.\n\x0bReverseStop\x12\x0e.commonpb.Addr\x1a\x0f.commonpb.Empty\x12/\n\x04List\x12\x0f.commonpb.Empty\x1a\x16.clientpb.EndpointListB-Z+github.com/Veids/grdp2tcp/protobuf/clientpbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clientpb.client_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z+github.com/Veids/grdp2tcp/protobuf/clientpb'
  _ENDPOINTLIST._serialized_start=58
  _ENDPOINTLIST._serialized_end=91
  _CLIENTRPC._serialized_start=94
  _CLIENTRPC._serialized_end=348
# @@protoc_insertion_point(module_scope)
